# fly.toml app configuration file generated for dro on 2025-04-15T00:42:52-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dro'
primary_region = 'sjc'

[build]

[[mounts]]
  source = 'data'
  destination = '/root'
  initial_size = '384gb'

[http_service]
  internal_port = 2222
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 2222
  auto_stop_machines = 'off'
  auto_start_machines = false

  [[services.ports]]
    port = 22

[[vm]]
  size = 'a100-80gb'
  memory = '128gb'
  cpu_kind = 'performance'
  cpus = 16
  gpus = 1
